apiVersion: v1
kind: Service
metadata:
  labels:
    service: kafka-producer
  name: kafka-producer
spec:
  ports:
  - name: "5005"
    port: 5005
    targetPort: 5005
    nodePort: 30005
  selector:
    service: kafka-producer
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: kafka-producer
  name: kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: kafka-producer
  template:
    metadata:
      labels:
        service: kafka-producer
    spec:
      containers:
      - image: kosmopy/kafka-producer:v13.0.0
        name: kafka-producer
        imagePullPolicy: Always
        env:
        - name: KAFKA_URL
          valueFrom:
            configMapKeyRef:
              name: kafkaproducer-configmap
              key: KAFKA_URL
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: kafkaproducer-configmap
              key: KAFKA_TOPIC
        - name: PYTHONUNBUFFERED
          value: '0'
      restartPolicy: Always